name: CI Compliance

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r autorez/requirements.txt
          pip install pytest pytest-cov

      - name: Run unit tests with coverage
        env:
          PYTHONPATH: autorez
        run: |
          pytest -q autorez/tests --maxfail=1 --disable-warnings --cov=autorez/src --cov-report=term-missing --cov-fail-under=95 | cat

      - name: Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Security - pytector availability
        run: |
          python - <<'PY'
          import pytector
          print('pytector OK')
          PY

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@v3.81.6
        with:
          path: .
          base: ${{ github.event.pull_request.base.sha || github.sha }}
          head: ${{ github.event.pull_request.head.sha || github.sha }}

  release:
    if: github.ref == 'refs/heads/main'
    needs: [build-test, secret-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

